#!/usr/bin/env bash
set -euo pipefail

make

# Currently the bootloader only loads 32 sectors.
# (32 * 512 = 16384)
SIZE=$(du -b drewos-image | cut -f1)
if [ ${SIZE} -gt 16384 ]
then
    echo "Need to increase number of sectors read by the boot loader."
    exit 1
fi

qemu-system-x86_64 drewos-image
